name: 'setup-licensed-dev'
description: 'setup-licensed-dev for use in GitHub Actions workflows'
author: 'Navegos'
branding:
  icon: check
  color: green
inputs:
  github_token:
    description: 'Authentication token to use with the GitHub API'
    required: false
  version:
    description: 'The setup-licensed-dev version to install'
    required: true
  install-dir:
    description: 'The target install directory for the setup-licensed-dev executable'
    default: '/usr/local/bin'
    required: false
runs:
  using: 'node24'
  main: 'dist/index.js'