name: Verify cached license metadata

on:
  # run on pushes to main
  push:
    branches:
      - main
  # run on all pull request events
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # run on demand
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v7

    # setup action requirements
    - uses: actions/setup-node@v7
      with:
        node-version: 24

    - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073
      with:
        ruby-version: ruby

    # install and run this action
    - run: npm install --production --ignore-scripts
    - name: Run setup-licensed-dev
      uses: ./
      with:
        version: '4.x'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # run licensed-ci to check and update licenses
    - uses: licensee/licensed-ci@f1f6507544a9db25b0f4730230bfdf67a9c1bc90
      with:
        workflow: push_for_bots
        dependabot_skip: 'true'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cleanup_on_success: 'true'
